# Generated by Django 5.1.5 on 2025-01-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Status', models.BooleanField(default=True)),
                ('Completion_Time', models.DateTimeField()),
                ('Start_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
