# Generated by Django 5.1.5 on 2025-01-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list',
            name='Completion_Time',
            field=models.DateTimeField(null=True),
        ),
    ]
