# Generated by Django 5.1.5 on 2025-01-21 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0002_alter_todo_list_completion_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_list',
            name='Completion_Time',
        ),
    ]
